"""Export inference-only checkpoints into ``artifacts/models/`` so they can be committed.

The training checkpoints under ``runs/`` are resumable: they carry optimizer state, RNG
state and history, which roughly triples their size and is useless to anyone who only
wants to *run* the model. They are also gitignored, which meant the Gradio demo worked on
the machine that trained the models and nowhere else — a demo that cannot be shared is
not a demo.

This script strips each checkpoint to weights plus the embedded config, which is enough
to rebuild the model exactly, and writes it somewhere committable. `nano` is 4.95M
parameters, so the whole published set is small enough to live in git without a model hub.

The exported files are byte-for-byte reproducible from ``runs/`` and are regenerated by
``make export-models``; they are a convenience, never a source of truth. Every number in
``results/`` still comes from the training run itself.

Usage::

    python scripts/export_models.py            # export everything that exists
    python scripts/export_models.py --check    # fail if an export is missing or stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import torch

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "runs"
OUT = ROOT / "artifacts" / "models"

#: GitHub rejects files over 100 MB and warns above 50 MB. Exports larger than this stay
#: out of git; they are the ones destined for a model hub instead.
COMMIT_LIMIT_BYTES = 50 * 2**20

#: ``(exported name, source checkpoint, what it is)``.
EXPORTS: tuple[tuple[str, Path, str], ...] = (
    (
        "nano-base",
        RUNS / "nano" / "pretrain" / "final.pt",
        "nano tier, pretrained on the toy corpus",
    ),
    ("nano-sft", RUNS / "nano" / "sft" / "final.pt", "nano tier after completion-masked SFT"),
    (
        "nano-aligned",
        RUNS / "nano" / "dpo_nll" / "final.pt",
        "nano tier after SFT then DPO with the RPO-style NLL anchor",
    ),
    (
        "nano-draft",
        RUNS / "nano" / "distill" / "reverse_kl" / "final.pt",
        "279k-parameter student from on-policy reverse-KL distillation; the speculative draft",
    ),
    (
        "micro-tinystories",
        RUNS / "micro" / "tinystories" / "final.pt",
        "micro tier, pretrained on TinyStories -- the natural-language model",
    ),
)


def digest(path: Path) -> str:
    """Short content hash, so `--check` can tell stale from missing."""
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def export_one(source: Path, dest: Path) -> dict[str, Any]:
    """Strip a training checkpoint down to weights + config and write it."""
    payload: dict[str, Any] = torch.load(source, map_location="cpu", weights_only=False)
    if "config" not in payload:
        raise KeyError(f"{source} does not embed a config; it cannot be exported safely.")

    slim = {
        "version": payload["version"],
        "model": payload["model"],
        "config": payload["config"],
        # Keep the counters: they are what lets a reader confirm which run this came from.
        "state": payload.get("state", {}),
    }
    dest.parent.mkdir(parents=True, exist_ok=True)
    torch.save(slim, dest)
    n_params = sum(t.numel() for t in payload["model"].values() if isinstance(t, torch.Tensor))
    return {
        "params": n_params,
        "bytes": dest.stat().st_size,
        "source_bytes": source.stat().st_size,
        "step": slim["state"].get("step"),
        "sha256_16": digest(dest),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if any export is missing.")
    args = parser.parse_args()

    index: dict[str, Any] = {}
    missing: list[str] = []

    for name, source, description in EXPORTS:
        dest = OUT / f"{name}.pt"
        if not source.exists():
            if dest.exists():
                index[name] = {"description": description, "note": "kept; source run not present"}
                print(f"  {name}: source missing, keeping committed export")
            else:
                missing.append(f"{name} (no {source.relative_to(ROOT)})")
                print(f"  {name}: SKIP - {source.relative_to(ROOT)} does not exist")
            continue

        if args.check:
            if not dest.exists():
                missing.append(f"{name} (never exported)")
            continue

        info = export_one(source, dest)
        committable = info["bytes"] <= COMMIT_LIMIT_BYTES
        index[name] = {
            "description": description,
            "source": str(source.relative_to(ROOT)),
            "committed": committable,
            **info,
        }
        note = "" if committable else "  [too large for git -- publish to a model hub]"
        print(
            f"  {name}: {info['params']:>10,} params  "
            f"{info['source_bytes'] / 2**20:5.1f} MB -> {info['bytes'] / 2**20:5.1f} MB{note}"
        )

    if args.check:
        if missing:
            print("missing exports: " + ", ".join(missing), file=sys.stderr)
            return 1
        print("all model exports present.")
        return 0

    (OUT / "index.json").write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")
    total = sum(v.get("bytes", 0) for v in index.values())
    committed = sum(v.get("bytes", 0) for v in index.values() if v.get("committed"))
    print(
        f"\nwrote {len(index)} models to {OUT.relative_to(ROOT)} "
        f"({total / 2**20:.1f} MB total, {committed / 2**20:.1f} MB committable)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
