"""Generate and commit a fixed set of samples from a checkpoint.

The samples in ``results/samples/`` are the qualitative counterpart to the loss curve:
they are regenerated by this script under fixed seeds, so a reviewer can check that the
text quoted in the README is what the committed weights actually produce.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch

from nanoscale.model import build_model
from nanoscale.tokenizer import BPETokenizer
from nanoscale.train.checkpoint import load_checkpoint, load_config_from_checkpoint
from nanoscale.utils import git_sha, hardware_string, resolve_device

DEFAULT_PROMPTS = (
    "It was a sunny day. Lily went to the park with",
    "Tom wanted to find",
    "The wind was cold.",
    "But a red ball was",
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("checkpoint", type=Path)
    parser.add_argument("--tokenizer", type=Path, default=Path("artifacts/tokenizer/nano.json"))
    parser.add_argument("--out", type=Path, default=Path("results/samples"))
    parser.add_argument("--name", type=str, default="nano_base")
    parser.add_argument("--max-new-tokens", type=int, default=64)
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--top-p", type=float, default=0.95)
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument("--per-prompt", type=int, default=2)
    args = parser.parse_args()

    cfg = load_config_from_checkpoint(args.checkpoint)
    tok = BPETokenizer.load(args.tokenizer)
    device = resolve_device("cpu")
    model = build_model(cfg.model).to(device)
    load_checkpoint(args.checkpoint, model=model, restore_rng=False, map_location=device)
    model.eval()

    records: list[dict[str, object]] = []
    for prompt in DEFAULT_PROMPTS:
        ids = torch.tensor([tok.encode(prompt, add_bos=True)], device=device)
        for i in range(args.per_prompt):
            gen = torch.Generator().manual_seed(args.seed + i)
            out = model.generate(
                ids,
                max_new_tokens=args.max_new_tokens,
                temperature=args.temperature,
                top_p=args.top_p,
                eos_id=tok.eos_id,
                generator=gen,
            )
            records.append(
                {
                    "prompt": prompt,
                    "seed": args.seed + i,
                    "text": tok.decode(out[0].tolist(), skip_special=True),
                }
            )

    args.out.mkdir(parents=True, exist_ok=True)
    meta = {
        "checkpoint": str(args.checkpoint),
        "git_sha": git_sha(),
        "hardware": hardware_string(),
        "temperature": args.temperature,
        "top_p": args.top_p,
        "params": model.num_parameters(),
        "samples": records,
    }
    (args.out / f"{args.name}.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")

    lines = [
        f"# Samples — `{args.name}`",
        "",
        f"Generated by `scripts/sample_generations.py` at git `{meta['git_sha']}` from "
        f"`{args.checkpoint}` ({model.num_parameters():,} parameters), "
        f"temperature {args.temperature}, top-p {args.top_p}.",
        "",
    ]
    for rec in records:
        lines += [f"**Prompt** (seed {rec['seed']}): `{rec['prompt']}`", "", f"> {rec['text']}", ""]
    (args.out / f"{args.name}.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote {args.out / args.name}.json and .md ({len(records)} samples)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
