"""Measure a trained tokenizer and write the numbers to ``results/tokenizer/``.

Every number quoted about the tokenizer in the README or the docs comes from this
script (spec A3.5). Run it with ``make tokenizer``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from nanoscale.data.toy import generate_corpus, iter_stories
from nanoscale.tokenizer import BPETokenizer
from nanoscale.utils import git_sha, hardware_string

#: A fixed out-of-domain passage (public domain: Orwell, *1984*, 1949).
OUT_OF_DOMAIN = (
    "It was a bright cold day in April, and the clocks were striking thirteen. "
    "Winston Smith, his chin nuzzled into his breast in an effort to escape the "
    "vile wind, slipped quickly through the glass doors of Victory Mansions."
)


def measure(tok: BPETokenizer) -> dict[str, Any]:
    """Compute the tokenizer's headline statistics."""
    held_out = "\n\n".join(iter_stories(seed=987_654, n_stories=200))
    train_like = generate_corpus(seed=1337, n_stories=200)
    longest = sorted(
        (piece for tid, piece in tok.vocab.items() if tid not in tok.id_to_special),
        key=len,
        reverse=True,
    )[:15]
    return {
        "vocab_size": tok.vocab_size,
        "merges_learned": tok.n_merges,
        "merges_targeted": tok.config.n_merges,
        "n_special_tokens": len(tok.special_to_id),
        "split_pattern": tok.config.split_pattern,
        "bytes_per_token_in_domain": round(tok.compression_ratio(train_like), 3),
        "bytes_per_token_held_out": round(tok.compression_ratio(held_out), 3),
        "bytes_per_token_out_of_domain": round(tok.compression_ratio(OUT_OF_DOMAIN), 3),
        "longest_tokens": [p.decode("utf-8", errors="backslashreplace") for p in longest],
        "git_sha": git_sha(),
        "hardware": hardware_string(),
    }


def render_markdown(stats: dict[str, Any]) -> str:
    """Render the stats as a committed markdown table."""
    lines = [
        "# Tokenizer report",
        "",
        f"Generated by `scripts/tokenizer_report.py` at git `{stats['git_sha']}`.",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Vocabulary size | {stats['vocab_size']} |",
        f"| Merges learned | {stats['merges_learned']} / {stats['merges_targeted']} |",
        f"| Special tokens | {stats['n_special_tokens']} |",
        f"| Pre-tokenization | `{stats['split_pattern']}` |",
        f"| Bytes/token, in-domain | {stats['bytes_per_token_in_domain']} |",
        f"| Bytes/token, held-out seed | {stats['bytes_per_token_held_out']} |",
        f"| Bytes/token, out-of-domain prose | {stats['bytes_per_token_out_of_domain']} |",
        "",
        "The out-of-domain figure is deliberately reported: a 1k-token vocabulary trained",
        "on a 3 MB synthetic corpus compresses unseen literary prose far worse than a",
        "web-scale tokenizer, and hiding that would be dishonest. The `micro` tier trains",
        "its 16k vocabulary on FineWeb-Edu and does not have this gap.",
        "",
        "## Longest learned tokens",
        "",
        "```",
        *[f"{t!r}" for t in stats["longest_tokens"]],
        "```",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tokenizer", type=Path, default=Path("artifacts/tokenizer/nano.json"))
    parser.add_argument("--out", type=Path, default=Path("results/tokenizer"))
    args = parser.parse_args()

    tok = BPETokenizer.load(args.tokenizer)
    stats = measure(tok)
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "nano.json").write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")
    (args.out / "nano.md").write_text(render_markdown(stats), encoding="utf-8")
    print(json.dumps({k: v for k, v in stats.items() if k != "longest_tokens"}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
